#!/bin/bash
#	Description:	
#	
#	Author: 	Simon Arjuna Erat, erat.simon@gmail.com
#	Date:		2015-06-16
#
#	This script requires TUI - Text User Interface & tui-browser  by (sea)
#	Check if TUI is installed...
#
	if ! which tui 2>/dev/zero 1>/dev/zero
	then 	[[ ! 0 -eq $UID ]] && \
			printf "\n#\n#\tPlease restart the script as root to install TUI (Text User Interface).\n#\n#\n" && \
			exit 1
		if ! git clone https://github.com/sri-arjuna/tui.git /tmp/tui.inst
		then 	mkdir -p /tmp/tui.inst ; cd /tmp/tui.inst/
			curl --progress-bar -L https://github.com/sri-arjuna/tui/archive/master.zip -o master.zip
			unzip master.zip && rm -f master.zip
			mv tui-master/* . ; rmdir tui-master
		fi
    		sh /tmp/tui.inst/install.sh || \
    			(printf "\n#\n#\tPlease report this issue of TUI installation fail.\n#\n#\n";exit 1)
    	fi
	. tuirc
	. /etc/connect.conf
#
#	Variables
#
	APP_VERSION=0.3
	ME="${0##*/}"
	ME_DIR="${0/$ME}}"
	ME_BASE="$DATADIR"
	ME_MENU="$DATADIR/to"
	TITLE="Connect ($APP_VERSION)"
	MORE_OPTS=""
	DIR_CFG="$HOME/.config/connect"
	export DIR_CFG
	TERM="${TERM:-GNU/linux}"
#
#	Help text
#
	help_text="
$ME ($script_version)
${TITLE^}
Usage: 		$ME [options] TASK [options] LABEL

"
	case "$1" in
	-h|--help)	printf '%s\n' "$help_text"
			exit 99
			;;
	-q|--quiet)	export beQuiet=true
			MORE_OPTS+=" -q"
			shift
			;;
	esac
#
#	Display to user
#
	#cd "$ME_BASE"
	tui-bol-root || tui-status 111 "It is recomended to run $ME as root!"
	tui \
		-p "$ME_MENU" \
		-T "$TITLE" \
		-c "$DIR_CFG/connect.conf" \
		$MORE_OPTS "${@}"
