.TH "connect" "1" "2015-06-16" "sea"

.SH NAME
connect (0.1)

.SH SYNOPSIS
\fBconnect\fP [options] nas|wifi [LABEL]
.br
Example: connect wifi LABEL
.br
Where options are:
.IP "\fB-h\fP"
Helpscreen
.IP "\fB-YX\fP"
does that

.SH DESCRIPTION
.PP
Connects to different devices.

.SH LICENSE
GNU General Public License (GPL)
.br
http://www.gnu.org/licenses/gpl.html

.SH CONTACT
erat.simon@gmail.com
.br
linux-scripter.blogspot.ch